name: Keep Streamlit App Alive

on:
  schedule:
    # Esegue l'azione ogni 8 ore (00:00, 04:00, 08:00, ecc.)
    - cron: '0 */8 * * *'
  workflow_dispatch: # Ti permette anche di avviarlo manualmente da GitHub se vuoi provarlo

jobs:
  ping-app:
    runs-on: ubuntu-latest
    steps:
      - name: Invia Ping HTTP all'app Streamlit
        run: |
          curl -s https://myclimbing.streamlit.app > /dev/null
          echo "Ping inviato con successo!"